[project]
authors = [{ name = "pablovela5620", email = "pablovela5620@gmail.com" }]
description = "Add a short description here"
name = "rerun-prompt-da"
requires-python = ">= 3.12"
version = "0.1.0"
dependencies = [
    "numpy",
    "av>=16.0.1,<17",
    "transformers",
    "rerun-sdk",
    "jaxtyping",
    "einops",
    "beartype",
    "pyserde",
    "tyro",
    "icecream",
    "pillow>=8.0,<12.0",
    "torch>=2.7.0",
    "pytorch-lightning",
    "opencv-python",
    "tqdm",
    "simplecv",
    "monopriors",
    "eclipse-zenoh>=1.8.0",
    "open3d ; platform_machine != 'aarch64'",
    "open3d-unofficial-arm ; platform_machine == 'aarch64'",
]

[project.scripts]
polycam-prompt-da = "rerun_prompt_da.cli:main"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.uv.sources]
simplecv = { git = "https://github.com/pablovela5620/simplecv.git" }
monopriors = { git = "https://github.com/pablovela5620/monoprior.git" }
torch = { index = "pytorch-cu130" }
onnxruntime-gpu = { index = "jetson-ai-lab" }

[tool.uv]
override-dependencies = [
  "onnxruntime-gpu ; platform_machine != 'aarch64'",
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[[tool.uv.index]]
name = "jetson-ai-lab"
url = "https://pypi.jetson-ai-lab.io/sbsa/cu130"
explicit = true
